### ISSUE TITLE
create a plugin.json?

### ISSUE THREAD

**Issue by psifertex** [matteyeux/seprom-loader#1]
Mind following the [plugin creation process](https://binary.ninja/2019/07/04/plugin-manager-2.0.html) and adding a plugin.json and creating a release so we can add this plugin to the UI Plugin Manager?

**Comment by matteyeux** [comment]
Hey Jordan !

I just added the plugin.json and created a release [tag](https://github.com/matteyeux/seprom-loader/releases/tag/1.0) according to the process. Let me know if I missed something

**Comment by psifertex** [comment]
You've got to actually create a release, not just the tag. You can do that through the UI or the `hub` CLI tool. See: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release

**Comment by psifertex** [comment]
You can tell it's working when: https://api.github.com/repos/matteyeux/seprom-loader/releases has content

**Comment by matteyeux** [comment]
Okay, release created. And the URL returns the JSON content.

**Comment by psifertex** [comment]
Added, thanks. :-)
