### ISSUE TITLE
stable is out

### ISSUE THREAD

**Issue by psifertex** [matteyeux/seprom-loader#2]
Super, super minor, but I noticed that https://github.com/matteyeux/seprom-loader/blob/master/seprom.py#L169 can be updated with the new stable launched yesterday.

Incredibly low priority of course, just mentioning it for whenever you happen to touch that code again as it's a very small cleanup.

**Comment by matteyeux** [comment]
Hey,
[Latest commit](https://github.com/matteyeux/seprom-loader/commit/b0ee82063de84ba84d51da9ea33240a07056b6d0) fixes it. And I created a new release, let me know if I have to fill a PR for the community plugins repo.

Also, you might want to inform the devs of [iBoot64binja](https://github.com/BlackwingHQ/iBoot64Binja)  as I used their [code](https://github.com/BlackwingHQ/iBoot64Binja/blob/master/modules/iboot64.py#L367).

**Comment by psifertex** [comment]
You're good, letting me know here is enough. 

Ugh, ignore my earlier comment, I was editing the wrong entry. 🤣

All set. Thanks.
