### ISSUE TITLE
please update version on next release

### ISSUE THREAD

**Issue by psifertex** [matteyeux/seprom-loader#3]
When you make a new update please make sure to update the [version string](https://github.com/matteyeux/seprom-loader/blob/master/plugin.json#L21) in the plugin.json file, not just the release tag/name when you do a new release. Not a big deal for now, just something for next time.

**Comment by matteyeux** [comment]
My bad ! I'll keep this issue open until next release, so I don't forget about it. Sorry for the inconvenience.

**Comment by psifertex** [comment]
Thanks! Not a huge deal, but definitely nice to have it be consistent. :-) I was worried at first the plugin manager wouldn't install the right version as a result, but it does so it's mostly just a cosmetic issue.
